[2024-09-09T20:58:24.250-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-09T20:58:24.262-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simple_dbt_dag.dag_dbt_raw_model manual__2024-09-09T23:53:18.247611+00:00 [queued]>
[2024-09-09T20:58:24.267-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simple_dbt_dag.dag_dbt_raw_model manual__2024-09-09T23:53:18.247611+00:00 [queued]>
[2024-09-09T20:58:24.268-0300] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-09-09T20:58:24.278-0300] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): dag_dbt_raw_model> on 2024-09-09 23:53:18.247611+00:00
[2024-09-09T20:58:24.281-0300] {standard_task_runner.py:72} INFO - Started process 259582 to run task
[2024-09-09T20:58:24.283-0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'simple_dbt_dag', 'dag_dbt_raw_model', 'manual__2024-09-09T23:53:18.247611+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/dag_dbt_raw_model.py', '--cfg-path', '/tmp/tmprkwmismb']
[2024-09-09T20:58:24.284-0300] {standard_task_runner.py:105} INFO - Job 10: Subtask dag_dbt_raw_model
[2024-09-09T20:58:24.325-0300] {task_command.py:467} INFO - Running <TaskInstance: simple_dbt_dag.dag_dbt_raw_model manual__2024-09-09T23:53:18.247611+00:00 [running]> on host DESKTOP-0CT35O1.
[2024-09-09T20:58:24.375-0300] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Matheus' AIRFLOW_CTX_DAG_ID='simple_dbt_dag' AIRFLOW_CTX_TASK_ID='dag_dbt_raw_model' AIRFLOW_CTX_EXECUTION_DATE='2024-09-09T23:53:18.247611+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-09T23:53:18.247611+00:00'
[2024-09-09T20:58:24.376-0300] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-09T20:58:24.377-0300] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-09T20:58:24.379-0300] {logging_mixin.py:190} INFO - Current task name:dag_dbt_raw_model state:running start_date:2024-09-09 23:58:24.263375+00:00
[2024-09-09T20:58:24.380-0300] {logging_mixin.py:190} INFO - Dag name:simple_dbt_dag and current dag run status:running
[2024-09-09T20:58:24.380-0300] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-09T20:58:24.382-0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-09T20:58:24.383-0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'pyenv activate dbt_env']
[2024-09-09T20:58:24.388-0300] {subprocess.py:86} INFO - Output:
[2024-09-09T20:58:24.415-0300] {subprocess.py:93} INFO - /usr/bin/bash: line 1: pyenv: command not found
[2024-09-09T20:58:24.416-0300] {subprocess.py:97} INFO - Command exited with return code 127
[2024-09-09T20:58:24.426-0300] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/mnt/c/Users/teu20/Documents/Poli/Repo/eEDB011-20243/atividade 6 - WSL/airflow/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/mnt/c/Users/teu20/Documents/Poli/Repo/eEDB011-20243/atividade 6 - WSL/airflow/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/mnt/c/Users/teu20/Documents/Poli/Repo/eEDB011-20243/atividade 6 - WSL/airflow/airflow_env/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/mnt/c/Users/teu20/Documents/Poli/Repo/eEDB011-20243/atividade 6 - WSL/airflow/airflow_env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/mnt/c/Users/teu20/Documents/Poli/Repo/eEDB011-20243/atividade 6 - WSL/airflow/airflow_env/lib/python3.10/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-09-09T20:58:24.440-0300] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-09-09T20:58:24.441-0300] {logging_mixin.py:190} INFO - Task start:2024-09-09 23:58:24.263375+00:00 end:2024-09-09 23:58:24.440341+00:00 duration:0.176966
[2024-09-09T20:58:24.442-0300] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): dag_dbt_raw_model> dag:<DAG: simple_dbt_dag> dagrun:<DagRun simple_dbt_dag @ 2024-09-09 23:53:18.247611+00:00: manual__2024-09-09T23:53:18.247611+00:00, state:running, queued_at: 2024-09-09 23:53:18.265354+00:00. externally triggered: True>
[2024-09-09T20:58:24.444-0300] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 127.
[2024-09-09T20:58:24.445-0300] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=simple_dbt_dag, task_id=dag_dbt_raw_model, run_id=manual__2024-09-09T23:53:18.247611+00:00, execution_date=20240909T235318, start_date=20240909T235824, end_date=20240909T235824
[2024-09-09T20:58:24.453-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-09T20:58:24.455-0300] {standard_task_runner.py:124} ERROR - Failed to execute job 10 for task dag_dbt_raw_model (Bash command failed. The command returned a non-zero exit code 127.; 259582)
Traceback (most recent call last):
  File "/mnt/c/Users/teu20/Documents/Poli/Repo/eEDB011-20243/atividade 6 - WSL/airflow/airflow_env/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/mnt/c/Users/teu20/Documents/Poli/Repo/eEDB011-20243/atividade 6 - WSL/airflow/airflow_env/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/mnt/c/Users/teu20/Documents/Poli/Repo/eEDB011-20243/atividade 6 - WSL/airflow/airflow_env/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/mnt/c/Users/teu20/Documents/Poli/Repo/eEDB011-20243/atividade 6 - WSL/airflow/airflow_env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/mnt/c/Users/teu20/Documents/Poli/Repo/eEDB011-20243/atividade 6 - WSL/airflow/airflow_env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/mnt/c/Users/teu20/Documents/Poli/Repo/eEDB011-20243/atividade 6 - WSL/airflow/airflow_env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/mnt/c/Users/teu20/Documents/Poli/Repo/eEDB011-20243/atividade 6 - WSL/airflow/airflow_env/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/mnt/c/Users/teu20/Documents/Poli/Repo/eEDB011-20243/atividade 6 - WSL/airflow/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/mnt/c/Users/teu20/Documents/Poli/Repo/eEDB011-20243/atividade 6 - WSL/airflow/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/mnt/c/Users/teu20/Documents/Poli/Repo/eEDB011-20243/atividade 6 - WSL/airflow/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/mnt/c/Users/teu20/Documents/Poli/Repo/eEDB011-20243/atividade 6 - WSL/airflow/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/mnt/c/Users/teu20/Documents/Poli/Repo/eEDB011-20243/atividade 6 - WSL/airflow/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/mnt/c/Users/teu20/Documents/Poli/Repo/eEDB011-20243/atividade 6 - WSL/airflow/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/mnt/c/Users/teu20/Documents/Poli/Repo/eEDB011-20243/atividade 6 - WSL/airflow/airflow_env/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/mnt/c/Users/teu20/Documents/Poli/Repo/eEDB011-20243/atividade 6 - WSL/airflow/airflow_env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/mnt/c/Users/teu20/Documents/Poli/Repo/eEDB011-20243/atividade 6 - WSL/airflow/airflow_env/lib/python3.10/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-09-09T20:58:24.497-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-09T20:58:24.511-0300] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-09T20:58:24.512-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
